Esri/calcite-app-components

- src/components/calcite-tip-manager/calcite-tip-manager.tsx
- src/components/calcite-tip-manager/resources.ts
- src/components/calcite-tip/calcite-tip.tsx
- src/components/calcite-tip/resources.ts
**Related Issue:** #104
Tip and Tipmanager need strings for some of their buttons.
Add i18n strings for tip buttons
> Add i18n strings for tip buttons

- .npmrc
- package-lock.json
- package.json
- Update @stencil/core to v1.2.5
- Also add `.npmrc` file to make save-exact true by default
- All tests are passing.
- Demos look unaffected.
> update @stencil/core to v1.2.5

- src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
- src/components/calcite-shell-panel/calcite-shell-panel.scss
- src/components/calcite-shell-panel/calcite-shell-panel.tsx
**Related Issue:** #164 
add collapsed property to hide shell panel content
> #164 add collapsed property to hide content

- src/assets/styles/includes.scss
**Related Issue:** #177 
Using exact file names for partials plays better with Stencil's watch mode. ~I'll create a separate Stencil bug for this since dropping the underscore in partials is a common Sass pattern.~ Possibly related to https://github.com/ionic-team/stencil-sass/issues/8.
> Issue #177: Reference partials by exact name to ensure rebuild.

- README.md
- package.json
- src/demos/head.js
- stencil.config.ts
- stencil.docs.config.ts
**Related Issue:** #182 
The shared `calcite` namespace was causing issues when both component libs were being used side-by-side.
**Note**: this does not change the component or event namespaces.
> Issue #182: Use different component namespace for build

- package-lock.json
- package.json
- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action/calcite-action.tsx
- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/utils/dom.ts
**Related Issue:** #190
The way `calcite-components` utils are being referenced is causing the build to bundle unrelated components in the dist. This inlines the utility, since it's pretty small at the moment, to avoid the issue. Ideally, we can create a separate repo/module to host these shared utilities.
> Issue #190: Inline calcite-component utilities to avoid unnecessary bundling

- src/components/calcite-action-pad/calcite-action-pad.scss
- src/components/calcite-action-pad/calcite-action-pad.tsx
- src/components/calcite-action-pad/resources.ts
- src/components/calcite-flow-item/calcite-flow-item.scss
- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-flow-item/resources.ts
- src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.scss
- src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.tsx
- src/components/calcite-shell-floating-panel/resources.ts
- src/demos/calcite-shell-rtl.html
- src/demos/calcite-shell.html
**Related Issue:** #185
- Adds positioning fixes for the floating panel and action pad
- positioning depends on shell panel leading/trailing value
- adds RTL support
- Fixes rtl support for `calcite-flow-item` menu
- Adds shell demo file for RTL 
Bug: calcite-floating-panel appears on wrong side #185
@jcfranco @asangma  can we make this higher priority? @AdelheidF needs this fix to continue work.
> Component positioning & RTL fixes

- src/components/calcite-flow-item/calcite-flow-item.e2e.ts
**Related Issue:** none
A minor annoyance when running the test suite - every so often the flow-item e2e tests would fail.
**File:** `src\components\calcite-flow-item\calcite-flow-item.e2e.ts`
**Line Number:** 127
This test was intermittently erroring on the above line. I suspect the `await page.waitForChanges()` wasn't properly waiting for the click to happen. So the tests suite would sometimes finish running and cleanup before that promise returned, causing the element to no longer be there by the time the click happen. Moving the await keyword in front of the click method call seems to fix this, and also makes it so we don't need `await page.waitForChanges()`
Ran the test suite like 5 times and stopped seeing this error. Seems like this fixed it.
> fix flow-item test intermittent errors

- src/components/calcite-block-section/calcite-block-section.e2e.ts
- src/components/calcite-block/calcite-block.e2e.ts
- src/tests/commonTests.ts
**Related Issue:** #207
This adds common tests helpers to reduce boilerplate for common tests across components. This initially updates `calcite-block` components, but will submit follow-up PRs for other components to minimize conflicts.
> Issue #207: Add common test util

- src/components/calcite-action-bar/calcite-action-bar.e2e.ts
- src/components/calcite-action-group/calcite-action-group.e2e.ts
- src/components/calcite-action-pad/calcite-action-pad.e2e.ts
- src/components/calcite-action/calcite-action.e2e.ts
- src/components/calcite-example/calcite-example.e2e.ts
- src/components/calcite-flow-item/calcite-flow-item.e2e.ts
- src/components/calcite-flow/calcite-flow.e2e.ts
- src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.e2e.ts
- src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
- src/components/calcite-shell/calcite-shell.e2e.ts
- src/components/calcite-tip-group/calcite-tip-group.e2e.ts
- src/components/calcite-tip/calcite-tip.e2e.ts
**Related Issue:** #207 
Updates other tests to use any applicable test helpers (mostly `renders` and `hidden`).  
Note that I left `calcite-tip-manager` alone since it was showing some console errors (JSHandle@object) when I switched them over to the utils.
> Issue #207: Update other E2E tests to use utility.

- package-lock.json
- package.json
This removes the `calcite-fonts` dependency, which is not being used. I diffed two different builds with and without it and there were no changes besides the order of `entries` in `collection/collection-manifest.json`.
> Drop unneeded dependency

- tslint.json
Per today's meeting, changing severity of `prefer-conditional-expression` rule to warning.
> Change prefer-conditional-expression rule severity to warning.

- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action-bar/readme.md
- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-block/readme.md
- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-flow-item/readme.md
- src/components/calcite-shell-panel/calcite-shell-panel.tsx
- src/components/calcite-shell-panel/readme.md
- src/components/calcite-shell/calcite-shell.tsx
- src/components/calcite-shell/readme.md
- src/components/calcite-tip/calcite-tip.tsx
- src/components/calcite-tip/readme.md
**Related Issue:** #192
Uses JSDoc to have the Stencil build auto-generate slot doc.
**Note**: Doc will be updated on `master` after merging.
cc @kat10140
> Issue 192: Use JSDoc for slots.

- src/components/calcite-pick-list/calcite-pick-list.e2e.ts
- src/components/calcite-pick-list/calcite-pick-list.tsx
**Related Issue:** #274 
pre-selected items in a pickList are now added to the selectedValues map on initial load. This means the list of selectedValues will now be correct when setting pre-selected items on the pickList.
> fix: pre-populate state with preselected items

- src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
**Related Issue:** #
Fixed the test. Puppeteer click() method will fail if the element you're trying to click is not visible. This will happen if it has zero width and zero height so for the pick-list-item I had to give it a heading so it had some content.
> fix: pick list needs to be visible to be clicked by puppeteer

- src/components/calcite-tip-manager/calcite-tip-manager.tsx
**Related Issue:** #258
* This removes the @Prop tabindex.
* Preserve arrow navigation functionality
* Respects user-defined tabindex.
> refactor: remove tabindex @Prop

- src/components/calcite-pick-list/calcite-pick-list.tsx
In order to avoid generating breaking changes with this release, we're deprecating but keeping props no longer used on the PickList.
* Adding back `textHeading` prop but marking it deprecated in JSDoc.
* Also deprecating `mode` and `dragEnabled` as these will be removed once valueList is merged. Could wait to deprecate these until that's ready.
> deprecating props on pickList

- package-lock.json
- package.json
- src/assets/styles/_color.scss
- src/assets/styles/includes.scss
Moves the `@esri/calcite-colors` dep to NPM.
**Note**: I had to move over some CSS vars because of [this @esri/calcite-base commit](https://github.com/Esri/calcite-base/commit/bc5d4fc50a4ec93fba852e6045995d684792289f#diff-2a6d07eef8b10b84129b42424ed99327).
> Change @esri/calcite-colors version to NPM package.

- src/components/calcite-pick-list/calcite-pick-list.tsx
**Related Issue:** #274 
* There's some strange behavior happening in Adelheide's environment. Perhaps it's Maquette but the connectedCallback() for pickList is firing before the pick-list-items render.
So in order to get the pre-selection working I've had to move that logic to componentDidLoad.
* I've left it in setUpItems so it runs when the mutation observer callback fires. This means it gets called twice on first load but the Map prevents duplicate entries, so its ok. Could possibly clean this up more.
> add pre-select logic on componentDidLoad

- package.json
After reading up on this, it seems like it would be better to use `npm ci` instead of `npm install` for deployments. This will also be relevant when getting `travis` working.
https://docs.npmjs.com/cli/ci.html
>  replace npm install with npm ci in preversion script

- src/components/calcite-block/calcite-block.scss
**Related Issue:** #308
Tweaks CSS to keep focus outline visible.
@asangma I added some space to the top of a section to prevent the following:
**after spacing**
> Issue #308: Ensure Block header focus outline is visible.

- src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
- src/components/calcite-tip-manager/calcite-tip-manager.tsx
Bug: User should not be able to use arrow keys on tip manager navigation buttons 
Bug: Keyboard Users should be able to scroll content inside of a tip manager
**Related Issue:** 
#307 key navigation only works on specified target
#306 allow scrolling via arrows inside content
Fixes pagination text not updating. Needs key to know to update.
Fixes accessibility issues.
> #307 key navigation only works on specified target

- .travis.yml
**Related Issue:** #152
This will allow `master` to be built so the build status badge is updated properly.
cc @kat10140
> Issue #152: Add master to branch-building safelist.

- src/components/calcite-block-section/calcite-block-section.scss
- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/calcite-block/calcite-block.scss
Also updated section focus overlap.
Includes icon update for sections.
**Related Issue:** #308
cc @annelfitz
> Nixed animations to fix flicker.

- src/assets/styles/_base.scss
- src/components/calcite-action-bar/calcite-action-bar.scss
- src/components/calcite-action-pad/calcite-action-pad.scss
- src/components/calcite-block-section/calcite-block-section.scss
- src/components/calcite-block/calcite-block.scss
- src/components/calcite-filter/calcite-filter.scss
- src/components/calcite-panel/calcite-panel.scss
- src/components/calcite-shell/calcite-shell.scss
- src/components/calcite-tip-manager/calcite-tip-manager.scss
- src/components/calcite-tip/calcite-tip.scss
**Related Issue:** #175
Generally moved foreground and background color rules to higher level CSS blocks, e.g. `:host`.
Will make updates to pick-list, value-list, and pick-list-item as needed after #342 is merged.
> Light refactoring of background and foreground CSS var usage

- src/components/calcite-pick-list/calcite-pick-list.tsx
- src/components/calcite-value-list/calcite-value-list.tsx
Rename `action` slot to `menu-actions`. This is the slot we're providing MapMaker team to do list sorting, etc.
Going to consider the incorrect name a bug, and this a bug fix.
> fix: rename action to menu-actions slot in PickList and ValueList

- src/assets/styles/_color.scss
- src/components/calcite-pick-list-group/calcite-pick-list-group.scss
- src/components/calcite-pick-list/calcite-pick-list.scss
- src/components/calcite-value-list-item/calcite-value-list-item.scss
- src/components/calcite-value-list/calcite-value-list.scss
**Related Issue:** #364
Added bg-color rules for lists.
> fix(lists): added bg-color rules. 

- src/components/calcite-block-section/calcite-block-section.tsx
**Related Issue:** #370
cc @AdelheidF
> style(block-section): use small calcite-switch.

- src/components/calcite-block-section/calcite-block-section.scss
- src/components/calcite-block/calcite-block.scss
- src/components/calcite-panel/calcite-panel.scss
- src/components/calcite-value-list/calcite-value-list.scss
- src/demos/calcite-pick-list.html
- src/demos/calcite-shell-full-window.html
**Related Issue:** #217
Started with the padding for Block and quickly realized that this was related to broader spacing issues.
@kat10140 Would you mind checking how generally combined spacing is working together, e.g. when a section is inside a block which is inside a panel, etc. and be another pair of eyes.
I think I got the spacing generally working better.
Also updated some demos to help better test the UI stuff.
> General spacing fixes

- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/calcite-block/calcite-block.tsx
**Related Issue:** #292 
Moved a11y attrs down to shadow DOM in favor of obfuscating implementation details.
> Issue #292: Move block a11y attributes to shadow DOM.

- src/components/calcite-panel/calcite-panel.scss
- src/demos/calcite-flow-item.html
**Related Issue:** #407 
flow item demo updated with loading and disabled states, Alan made styling changes to panel to accommodate those toggles.
> Flow item demo and panel styling

- src/components/calcite-flow-item/calcite-flow-item.e2e.ts
- src/components/calcite-flow-item/calcite-flow-item.tsx
**Related Issue:** Bug: calcite-flow-item shows header-trailing-content without having menu-actions #409
Fixes an issue where the slot for menu actions isn't defined in the root but in another component which affects the rendering of the 3 dots icon showing when it shouldn't be showing.
See #409.
Fixed by making sure the slot is within the root of the element.
> Bug: calcite-flow-item shows header-trailing-content without having menu-actions

- src/components/calcite-panel/calcite-panel.tsx
**Related Issue:** #354
CalcitePanel: always render slot container nodes
- Removes conditional logic to test if a slot has been used. This benefits the flex positioning because if container isn't there the positioning is incorrect.
> CalcitePanel: always render slot containers. #354

- src/components/calcite-tip/calcite-tip.scss
**Related Issue:** #398 fix tip background color.
#398 fix tip background color.
The calcite-tip has a shadow inside of itself. The shadow should be either on the host or the background color should be defined where the shadow is.
> #398 fix tip background color

- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-value-list/calcite-value-list.tsx
**Related Issue:** ##424
Removed unused `disabled` from descruture.
> bug(value-list): nixed disabled prop from destruct

- package-lock.json
- package.json
**Related Issue:** #441 
`stencil@1.7.2` causes the docs build to fail if a non-doc build is run before (it picks up all `d.ts` files and will complain if there are duplicate definitions). This will clean up generated `components.d.ts` files before the docs build runs.
I'll bump versions on the master branch after this lands.
> Issue #441: Clean up generated d.ts files before running docs.

- src/components/calcite-value-list-item/calcite-value-list-item.scss
**Related Issue:** #456
Remove redundant padding.
This PR refrains from some needed styling that is coming in #458
> fix(value-list-item): removed redundant padding

- src/components/calcite-block/calcite-block.scss
**Related Issue:** #453
Fixed block caret icon size change when title is long.
> Fixed block caret icon size change when title is long.

- src/components/calcite-block/calcite-block.e2e.ts
- src/components/calcite-block/calcite-block.scss
- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-block/resources.ts
- src/demos/calcite-block.html
**Related Issue:** #404
Adds slot (name => `"icon"`) for trailing header icon.
@asangma Can you review the spacing between the icon and header? It may need some tweaking.
> Issue #404: Add icon slot for calcite block header .

- src/components/calcite-block/calcite-block.e2e.ts
- src/components/calcite-block/calcite-block.tsx
- src/demos/calcite-block.html
**Related Issue:** #403
This hides the collapsible icon (downward/upward chevron) whenever there is a control.
> Issue #403: Hide collapsible icon when control is provided.

- src/components/calcite-pick-list-item/calcite-pick-list-item.scss
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
**Related Issue:** #447
text-description is not rendered in compact mode.
> feat(pick-list-item): Exclude text-description in compact mode.

- src/components/calcite-panel/calcite-panel.scss
**Related Issue:**  (#472)
Panel. z-index for loading and disabled
> Added z-index for disabled and loading panel.

- src/components/calcite-action/calcite-action.scss
- src/components/calcite-action/calcite-action.tsx
- src/components/calcite-action/resources.ts
- src/components/calcite-flow-item/calcite-flow-item.tsx
- Fixes loading spinner to show without the SVG in the CalciteAction in Edge.
- The loading spinner was displaying above the SVG icon. This hides the svg when loading.
- Fixes footer display issue in CalciteFlowItem in Edge.
- A slot with another slot attribute won't work correctly in the Edge Polyfill
> fix: calcite-action loading & calcite-flow-item footer in Edge browser

- .gitignore
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-pick-list/calcite-pick-list.e2e.ts
- src/components/calcite-pick-list/calcite-pick-list.tsx
- src/components/calcite-pick-list/shared-list-logic.ts
- src/components/calcite-pick-list/shared-list-tests.ts
- src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
- src/components/calcite-tip-manager/calcite-tip-manager.spec.ts
- src/components/calcite-value-list-item/calcite-value-list-item.tsx
- src/components/calcite-value-list/calcite-value-list.e2e.ts
- src/components/calcite-value-list/calcite-value-list.tsx
**Related Issue:** #461, #400  
TL;DR; I've abstracted some shared code for PickList and ValueList.
In working on a couple bugs for the lists, I've realized that they are already starting to diverge in undesirable ways. From the get-go the test suite was more extensive on pick-list than value-list. And there was quite a bit of duplicated code. I left them isolated since it seemed like these might diverge more based on information from @asangma and @kat10140 but so far they are still very similar.
* Several methods have been abstracted to a new filed called `share-list-logic.ts` and both components are importing that as a dependency and use those functions for several internal methods.
* Several tests have been abstracted into `shared-list-tests.ts`, mainly the selection/deselection tests …
> PickList and ValueList: share more code between lists 461

- src/components/calcite-flow-item/calcite-flow-item.e2e.ts
- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-flow-item/resources.ts
**Related Issue:** #409
Filter out menu actions defined in the calcite-pick-list and calcite-value-list.
> fix: FlowItem - Filter out menu actions defined in the calcite-pick-list and calcite-value-list.

- src/components/calcite-flow-item/calcite-flow-item.scss
- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-flow-item/resources.ts
- src/components/calcite-panel/calcite-panel.scss
- src/demos/calcite-shell-full-window.html
**Related Issue:** #367 
Fixes layout of calcite-button (or other generic button) in panel footer. flow-item inherits the fix with a bit of additional styling.
Also updated full-window demo to use calcite-button.
> fix: flow-item and panel footer buttons

- src/components/calcite-action-pad/calcite-action-pad.scss
**Related Issue:** #506
Added missing styles to align with calcite-components.
cc @russroberts
> style(action-pad): added missed styles

- src/components/calcite-block-section/calcite-block-section.scss
**Related Issue:** #507
Removed redundant padding.
cc @AdelheidF
> style(block-section): missed style for switch mode

- src/components/calcite-block/calcite-block.e2e.ts
- src/demos/calcite-block.html
**Related Issue:** #402
Adds missing Block tests.
**Note**: Left similarities between tests as is. Extracting into a helper didn't make things clearer. Open to suggestions though. 😄
> test(block): add tests for loading and disabled properties

- src/components/calcite-block-section/calcite-block-section.scss
- src/demos/calcite-shell-full-window.html
**Related Issue:** #455
Added some spacing and RTL spacing for when block-section is in switch mode and the label is long.
Includes some updates to full-window demo.
> style(block-section): label spacing in switch mode

- src/assets/styles/_layout.scss
**Related Issue:** #516
Use CSS vars instead of Sass for calculating fractional values for sizes.
Note, this allow an app to do this and have it work for all calculated values.
```
:root {
--calcite-app-side-spacing: 24px;
--calcite-app-cap-spacing: 24px;
}
```
> refactor: use CSS vars for calculations

- src/components/calcite-filter/calcite-filter.scss
**Related Issue:** #340 
Removing the Edge specific clear button.
Reasoning: https://github.com/Esri/calcite-app-components/issues/340#issuecomment-551280340
> remove Edge's nonStandard broken clear btn

- src/components/calcite-value-list-item/calcite-value-list-item.scss
**Related Issue:** #517
Remove box-shadow (border) from last child.
> style(calcite-value-list-item) Remove box-shadow border from last child.

- src/components/calcite-value-list-item/calcite-value-list-item.scss
**Related Issue:**  (#542)
Last value-list-item was not getting a selected state.
> fix(value-list-item): last child selection

- src/assets/styles/_base.scss
- src/assets/styles/_layout.scss
- src/components/calcite-panel/calcite-panel.scss
- src/components/calcite-panel/calcite-panel.tsx
**Related Issue:** #547 
* Added a ternary to only render `header-leading-content` node when slot has content
* Updated related styles
* Includes a small fix for #554
> fix(panel): header-content layout when leading slot is empty

- src/assets/styles/_layout.scss
- src/components/calcite-action/calcite-action.scss
**Related Issue:** #569
Outline inset some to make sure focus is visible when action buttons are right next to each other.
@driskull @jcfranco  Hoping this can get into a patch for the beta. JB brought it to our attention.
> fix(action): focus outline a11y

- src/components/calcite-pick-list-item/calcite-pick-list-item.e2e.ts
- src/components/calcite-pick-list/shared-list-tests.ts
**Related Issue:** #423 
Previous tests were only validating the event was called. This validates the event detail object for the two event types is what's expected. This should help avoid bugs being introduced where the event data is modified unintentionally.
> Lists: added tests to validate event data

- src/components/calcite-action-bar/calcite-action-bar.e2e.ts
- src/components/calcite-action-group/calcite-action-group.e2e.ts
- src/components/calcite-action-pad/calcite-action-pad.e2e.ts
- src/components/calcite-action/calcite-action.e2e.ts
- src/components/calcite-action/calcite-action.tsx
- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-flow-item/calcite-flow-item.e2e.ts
- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-flow/calcite-flow.e2e.ts
- src/components/calcite-panel/calcite-panel.e2e.ts
- src/components/calcite-panel/calcite-panel.tsx
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-pick-list/shared-list-render.tsx
- src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
- src/components/calcite-shell/calcite-shell.e2e.ts
- src/components/calcite-tip-manager/calcite-tip-manager.tsx
- src/components/calcite-value-list-item/calcite-value-list-item.tsx
> test(a11y): wire up missing accessible tests.

- .stylelintrc.json
This enables a few more rules as discussed in a previous sync-up meeting.
> chore: Enable more style linting rules.

- src/components/calcite-flow/calcite-flow.tsx
- src/components/calcite-flow/resources.ts
- src/components/interfaces.ts
chore: Move Flow type to interfaces.ts
> chore: Move Flow type to interfaces.ts

- src/demos/demoPageReloader.js
- src/demos/head.js
fix: demo pages in IE11
- Only loads demopagereloader script if port 3333-3339
- Only loads toggles script if not IE (We can load this if its rewritten with IE support)
- Cleanup
> fix: demo pages in IE11

- src/components/calcite-value-list-item/calcite-value-list-item.scss
**Related Issue:** #573 
Focus ring for value-list-item handle.
> fix(value-list-item): focus outline for handle

- src/components/calcite-filter/calcite-filter.tsx
- src/components/calcite-value-list-item/calcite-value-list-item.tsx
- Keep value-list-item selected in sync with pick-list-item
- Add value to input. warning from stencil dev server `[STENCIL-DEV-MODE] The "value" prop of <input> should be set after "min", "max", "type" and "step"`
> fix: keep value-list-item selected in sync with pick-list-item

- src/components/calcite-flow/calcite-flow.e2e.ts
- src/components/calcite-flow/calcite-flow.tsx
**Related Issue:** #626
Fix animation being removed when the subtree of a flow changes during the animation
> fix: Flow animation being removed when subtree of flow-item changes

- src/components/calcite-action/calcite-action.tsx
chore: deprecate "textDisplay" in favor of "textEnabled"
> chore: deprecate "textDisplay" in favor of "textEnabled"

- src/assets/styles/_base.scss
- src/assets/styles/_layout.scss
- src/components/calcite-panel/calcite-panel.scss
**Related Issue:** #565
Partial fix. Developer will still need to only set heights on flow or container when in popover.
cc @AdelheidF
> fix(panel): add min-heights for panel header and footer

- src/components/calcite-panel/calcite-panel.scss
**Related Issue:** #642
Added better flex grow, shrink, basis for panel header and footer.
@driskull 
Could use a patch for this one.
> fix(panel): flex grow, shrink, basis for panel headers and footers

- package.json
- support/tempDocDirCleaner.js
**Related Issue:** #401 
The `docs:storybook` script currently hangs unless it's explicitly terminated (e.g., CTRL+C on Unix).
> chore(docs): ensure storybook doc build runs fully

- package-lock.json
- package.json
`npm-run-all` is redundant since we have `concurrently` and can be dropped.
> chore(deps): use concurrently instead of npm-run-all

- package.json
- stencil.docs.config.ts
- stencil.storybook.config.ts
* Restores `outputTargets` from doc-specific Stencil configs.
* Builds demo source before building docs.
> docs(demos): fix docs output

- src/components/calcite-block/calcite-block.stories.ts
Use property names for knobs for consistency.
> docs(calcite-block): update stories to use property name

- .storybook/preview-head.html
Adds missing stylesheet for `@esri/calcite-components`.
> docs(demos): add missing vendor stylesheet

- .storybook/utils.ts
**Related Issue:** #675 
Fixes markup generated by `createComponentHTML` helper.
> docs(demos): update HTML helper to add missing quotes for attribute values

- src/components/calcite-block/calcite-block.scss
- src/components/calcite-panel/calcite-panel.scss
- src/components/calcite-shell-panel/calcite-shell-panel.scss
- src/demos/shell/demo-app-full-window.html
**Related Issue:** #691 
- flex-flow rule for panel and shell-panel
- block spacing to take account of margin rendering in flex
- panel styles to ensure spacing stays accurate with blocks
> fix(panel, shell-panel): flex-flow fix

- .storybook/utils.ts
- src/components/calcite-action-bar/calcite-action-bar.stories.ts
- src/components/calcite-action-pad/calcite-action-pad.stories.ts
- src/components/calcite-action/calcite-action.stories.ts
- src/components/calcite-block/calcite-block.stories.ts
- src/components/calcite-flow/calcite-flow.stories.ts
- src/components/calcite-panel/calcite-panel.stories.ts
- src/components/calcite-pick-list/calcite-pick-list.stories.ts
- src/components/calcite-shell/calcite-shell.stories.ts
- src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
- src/components/calcite-tip/calcite-tip.stories.ts
- src/components/calcite-value-list/calcite-value-list.stories.ts
**Related Issue:** #674
Drops default page title to avoid duplicate one from README.
> docs(demos): hide duplicate title from docs tab

- src/components/calcite-shell-panel/usage/basic.md
- src/components/calcite-shell/usage/advanced.md
- src/components/calcite-shell/usage/basic.md
**Related Issue:** #619 #702 
Fixed the closing calcite-icon for shell snippets as well. Shell snippets were just merged, so hope it's ok to do it here
> docs: calcite shell panel snippets

- src/components/calcite-flow-item/calcite-flow-item.tsx
fix: prevent window scrolling when using arrow keys in flow-item menu
> fix: prevent window scrolling when using arrow keys in flow-item menu

- src/components/calcite-value-list/usage/basic.md
- src/demos/shell/basic.html
**Related Issue:** #619 #704 
I still have the slot as 'secondaryAction'. Let me know if you'd like to change this now or later?
> docs: calcite value list snippets

- src/components/calcite-action-bar/usage/basic.md
- src/components/calcite-action-pad/usage/basic.md
- src/components/calcite-action/usage/basic.md
- src/components/calcite-panel/usage/basic.md
- src/components/calcite-pick-list/usage/basic.md
- src/demos/shell/basic.html
**Related Issue:** #619 
Added <calcite-icon>s to the example snippets
> docs: snippet cleanup

- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-flow-item/resources.ts
- src/components/calcite-panel/calcite-panel.scss
**Related Issue:** FlowItem RTL trailing icon isn't on the far side #721
FlowItem RTL trailing icon isn't on the far side #721
> fix: FlowItem RTL trailing icon isn't on the far side #721

- src/components/calcite-block/calcite-block.scss
- src/components/calcite-pick-list/calcite-pick-list.scss
- src/components/calcite-value-list/calcite-value-list.scss
**Related Issue:** #565 
Might also fix #555 
Some minor updates that should complete fixes for Safari and retain good layout in Chrome.
@AdelheidF Checked this in map viewer beta. Requires removing height rules from pick-list and adding `height-scale="m" to panel`
> fix: addresses safari bugs with pick-list and value-list

- package.json
- stencil.config.ts
* `npm run test` and `npm run start` will no longer generated readme files for components.
* `npm run build` will still generated readme files.
> chore: change config so readme only built on prod build

- src/components/calcite-block/calcite-block.e2e.ts
- src/components/calcite-block/calcite-block.scss
- src/components/calcite-block/calcite-block.tsx
**Related Issue:** #751
This restructures `calcite-block`'s control slot to avoid unintentional toggling.
> fix(block): prevent unintentional toggling when interacting with a slotted control

- src/components/calcite-action-bar/calcite-action-bar.e2e.ts
- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action-pad/calcite-action-pad.e2e.ts
- src/components/calcite-action-pad/calcite-action-pad.tsx
- src/components/utils/CalciteExpandToggle.tsx
fix: only modify textEnabled when expand functionality is enabled
> fix: only modify textEnabled when expand functionality is enabled

- src/components/calcite-flow-item/calcite-flow-item.tsx
chore: cleanup rendering of the header in flow item
Doesn't alter the dom structure at all, there was just a private method not being used that should be.
> chore: cleanup rendering of the header in flow item

- src/components/calcite-block/calcite-block.scss
- src/components/calcite-flow-item/calcite-flow-item.scss
- src/components/calcite-flow/calcite-flow.scss
- src/components/calcite-shell-panel/calcite-shell-panel.scss
**Related Issue:** #771 
Don't call it a comeback...but the 100% heights are making a comeback.
When in non-detached mode, the flow-item footers were not sticking to the bottom.
Outside components being but into flow-item will still need to set their own heights (i.e. to 100%).
Would be nice to get this into a patch maybe?
> fix: nesting and height issues

- src/components/calcite-value-list-item/calcite-value-list-item.scss
- src/scss/mixins/_utilities.scss
- src/scss/mixins/variables/_layout.scss
- src/scss/mixins/variables/theme/_light.scss
**Related Issue:** #543
- updated focus style
- updated selected style
- refactored style to be more on value-list-item and less so on pick-list-item
Note: this is a temporary update until the broader focus designer are in.
> fix(value-list-item): focus state fix

- src/components/calcite-block/calcite-block.scss
- src/components/calcite-block/calcite-block.tsx
- src/demos/block/basic.html
**Related Issue:** #763 
This restores block toggling in Edge. The issue was caused by the 'has content' logic, which caused the block to never open after being closed (`el.children` in Edge includes the elements in the render function, tripping up the logic).
> fix(block): fix block toggling in Edge

- src/tests/commonTests.ts
The `reflects` test helper uses prop names as is to build a selector. This needed to be updated to handle the prop-to-attr mapping built into web components.
> chore(tests): update reflects test helper to handle camelCased props

- src/components/calcite-action/calcite-action.scss
**Related Issue:** #759
Additionally specific selectors for compact mode now that `scale` is a prop.
cc @kat10140
> fix(action): style updates for compact mode

- .storybook/utils.ts
- src/components/calcite-block/calcite-block.scss
- src/components/calcite-block/calcite-block.stories.ts
**Related Issue:** #791 
This removes unwanted padding on the icon slot. This was a regression from #763 (oversight on my part 😅).
> fix(block): Avoid extra padding applied to slotted icon content

- .storybook/resources.ts
- src/components/calcite-action-bar/calcite-action-bar.stories.ts
- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action-pad/calcite-action-pad.stories.ts
- src/components/calcite-action-pad/calcite-action-pad.tsx
- src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
- src/components/calcite-shell-panel/calcite-shell-panel.scss
- src/components/calcite-shell-panel/calcite-shell-panel.tsx
- src/components/calcite-shell/calcite-shell.e2e.ts
- src/components/calcite-shell/calcite-shell.stories.ts
- src/components/calcite-shell/calcite-shell.tsx
- src/components/calcite-shell/readme.md
- src/components/calcite-shell/usage/advanced.md
- src/components/calcite-shell/usage/basic.md
- src/components/interfaces.ts
- src/components/utils/CalciteExpandToggle.tsx
- src/components/utils/dom.ts
- src/demos/shell-panel/basic.html
- src/demos/shell/basic.html
- src/demos/shell/demo-app-full-window-reversed.html
- src/demos/shell/demo-app-full-window.html
- src/demos/shell/demo-app-rtl.html
- src/demos/shell/demo-app.html
- src/demos/shell/panel-with-action-bar.html
- Deprecate use of `layout` property.
- Add `position` property which can be `start` or `end`.
https://github.com/Esri/calcite-components/pull/325#discussion_r376087970
> feat: deprecate layout in favor of position

- src/demos/action-bar/add-action-after-init.html
- src/demos/action-bar/basic.html
- src/demos/action-pad/basic.html
- src/demos/action/add-action-icon-after-init.html
- src/demos/action/basic.html
- src/demos/block/basic.html
- src/demos/block/with-value-list.html
- src/demos/flow-item/basic.html
- src/demos/flow/adding-items.html
- src/demos/flow/basic.html
- src/demos/handle/basic.html
- src/demos/panel/basic.html
- src/demos/pick-list/advanced.html
- src/demos/pick-list/basic.html
- src/demos/shell-panel/basic.html
- src/demos/shell/basic.html
- src/demos/shell/demo-app-full-window-reversed.html
- src/demos/shell/demo-app-full-window.html
- src/demos/shell/demo-app-rtl.html
- src/demos/shell/demo-app.html
- src/demos/shell/panel-with-action-bar.html
- src/demos/sortable-list/basic.html
- src/demos/sortable-list/sortable-blocks.html
- src/demos/tip-manager/basic.html
- src/demos/tip/basic.html
- src/demos/value-list/advanced.html
- src/demos/value-list/basic.html
- src/demos/value-list/double-action.html
- src/demos/value-list/value-update.html
Addresses: 
* Inconsistent test page casing.
* Invalid HTML syntax.
* Unused vars.
* Global vars.
* Commented-out markup.
* Unused CSS classes.
* Unnecessary doc content (superseded by stories).
* Typos.
> chore(demos): tidy up test pages

- .storybook/config.ts
- .storybook/utils.ts
- src/components/calcite-action-bar/calcite-action-bar.stories.ts
- src/components/calcite-action-pad/calcite-action-pad.stories.ts
- src/components/calcite-action/calcite-action.stories.ts
- src/components/calcite-block/calcite-block.stories.ts
- src/components/calcite-flow/calcite-flow.stories.ts
- src/components/calcite-panel/calcite-panel.stories.ts
- src/components/calcite-pick-list/calcite-pick-list.stories.ts
- src/components/calcite-shell/calcite-shell.stories.ts
- src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
- src/components/calcite-tip/calcite-tip.stories.ts
- src/components/calcite-value-list/calcite-value-list.stories.ts
This fixes an issue with Docs content where an error is displayed when viewing component stories.
Also, this tidies up the common docs page used across stories.
> chore(storybook): fix docs content

- .storybook/utils.ts
**Related Issue:** #828
This changes the relative component doc URLs from auto-generated component doc when parsed for Storybook notes. These URLs are replaced with their respective link to this repo.
> docs(storybook): fix broken links to components from Storybook notes

- .storybook/addons.ts
- .storybook/main.ts
- .storybook/presets.ts
- .storybook/preview.ts
This updates our Storybook setup to what the latest doc suggests (namely: using `main.ts` + `preview.ts` and no longer using environment-specific presets).
> chore(docs): migrate Storybook setup to latest

- docs/iframe.html
This is a manual fix for https://github.com/storybookjs/storybook/issues/9900, which strips out the ` type="module"` from the component script tags.
Note that this only affects the storybook distributable, not the preview.
> docs: fix broken storybook build

- src/components/calcite-action/calcite-action.e2e.ts
- src/components/calcite-action/calcite-action.tsx
- src/demos/action/basic.html
Allow SVGs to be slotted into the calcite-action. At least temporarily until we can figure out a way to determine if the default slot is populated with an element.
> fix(Action): Allow SVGs to be slotted into the calcite-action.

- src/components/calcite-shell-panel/calcite-shell-panel.scss
- src/demos/shell/demo-app-full-window.html
**Related Issue:** #846
Added back styles for deprecated attributes.
> fix(shell-panel): style for deprecated leading and trailing attributes

- src/components/calcite-fab/calcite-fab.e2e.ts
- src/components/calcite-fab/calcite-fab.tsx
- src/components/calcite-fab/readme.md
- src/components/calcite-panel/calcite-panel.scss
- src/components/interfaces.ts
- src/demos/fab/basic.html
**Related Issue:** #815 
Minor updates. Mostly adding pass-through props.
> feat: props and style for fab

- src/components/calcite-block-section/calcite-block-section.e2e.ts
- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/calcite-block/calcite-block.e2e.ts
- src/components/calcite-block/calcite-block.stories.ts
- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-filter/calcite-filter.e2e.ts
- src/components/calcite-filter/calcite-filter.tsx
**Related Issue:** #818 
This adds `intl<name>` props to replace their applicable `text<name>` equivalents.
Also adds new `intlClose` property to filter since it had no text prop.
> feat(block, block-section, filter): add intl props

- src/components/calcite-block-section/calcite-block-section.e2e.ts
- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/calcite-block/calcite-block.e2e.ts
- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-filter/calcite-filter.e2e.ts
- src/components/calcite-filter/calcite-filter.tsx
**Related Issue:** #818 
This addresses omitted changes from this PR: https://github.com/Esri/calcite-app-components/pull/852#discussion_r384863609
> refactor(block, block-section, filter): make intl props optional and add fallbacks

- src/components/calcite-filter/calcite-filter.e2e.ts
- src/components/calcite-filter/calcite-filter.tsx
This adds `placeholder` to `calcite-filter`. This prop deprecates `textPlaceholder` since it does not have a default value and therefore does not need the `text` prefix.
> feat(filter): add placeholder property

- .storybook/utils.ts
**Related Issue:** #828 
This fixes the relative link replacement logic, which was only being applied to the first match.
**Note**: this also removes necessary escape char removal (markdown content renders fine without it).
cc @kat10140
> docs(storybook): fix all relative readme links

- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-tip-manager/calcite-tip-manager.tsx
- src/tests/utils.ts
> chore: use optional chaining wherever applicable

- src/components/calcite-flow-item/calcite-flow-item.tsx
**Related Issue:** See 1322 in webviewer repo.
- Added a check for the `fab` slot in flow-item
- `fab-container` will only show if the slot is used.
> fix(flow-item): update to only show fab-container when fab slot is used

- LICENSE.txt
- LICENSING.md
- README.md
- package.json
I followed the file structure you have for the licensing information. However, on all other repositories:
[calcite-color](https://github.com/Esri/calcite-colors)
[calcite-ui-icons](https://github.com/Esri/calcite-ui-icons)
[calcite-base](https://github.com/Esri/calcite-base/)
etc.
We just have the license information at the bottom of the readme file.
> docs(license): Update license

- src/components/calcite-action/calcite-action.tsx
- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-panel/calcite-panel.tsx
- stencil.config.ts
```ts
/**
* For browsers that do not support shadow dom (IE11 and Edge 18 and below), slot is polyfilled
* to simulate the same behavior. However, the host element's `childNodes` and `children`
* getters are not patched to only show the child nodes and elements of the default slot.
* Defaults to `false`.
*/
slotChildNodesFix?: boolean;
```
@jcfranco do you remember which component we were trying to find out if the default slot is populated?
> fix(action): Add slotChildNodesFix to stencil config extras

- stencil.config.ts
- tsconfig.json
The latest Stencil release deprecated `excludeSrc` from `stencil.config.ts` and instead uses  `tsconfig.json` for exclusions. This updates our config accordingly.
> chore: update project config

- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-block/resources.ts
- src/demos/block/basic.html
**Related Issue:** #896 
Removes block header caret per updated block design. 👋🥕
> feat(block): drop open/close icon

- src/components/calcite-block/calcite-block.scss
**Related Issue:** #849
This updates Block to use CSS grid for its layout to avoid an issue where a control may flow outside its container.
> fix(block): use CSS grid to improve header layout

- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-pick-list/calcite-pick-list.stories.ts
- src/components/calcite-value-list/calcite-value-list.stories.ts
Also updates other calcite-icons to not use filled attribute.
**Related Issue:** #902 
Drops `filled` attribute, which was dropped in the latest `calcite-components` release.
> fix(flow-item): fix back button icon not showing up

- package-lock.json
- package.json
Rollback `lint-staged` since it trips up the release script.
> build: fix release script

- src/components/calcite-action/calcite-action.tsx
- src/components/calcite-flow/calcite-flow.tsx
- src/components/calcite-pick-list/calcite-pick-list.tsx
- src/components/calcite-sortable-list/calcite-sortable-list.tsx
- src/components/calcite-tip-manager/calcite-tip-manager.tsx
- src/components/calcite-value-list/calcite-value-list.tsx
**Related Issue:** #919 
This addresses an issue that arose when components were used in another VDOM library ([maquette](https://github.com/AFASSoftware/maquette)) and children were added after `connectedCallback` (`MutationObserver` is initialized), but before `componentWillLoad` (`MutationObserver` starts observing), preventing some initialization logic from kicking in. 
cc @AdelheidF
> fix(action, flow, pick-list, sortable-list, tip-manager, value-list): react to DOM mutations earlier to avoid stagnant renders

- src/components/calcite-value-list/calcite-value-list.tsx
**Related Issue:** #919 
Moves value-list DND setup back to `componentDidLoad`. This shouldn't have moved in the first place since it doesn't kick in on DOM mutations.
cc @AdelheidF
> fix(value-list): restore DND setup

- package-lock.json
- package.json
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-pick-list-item/resources.ts
`calcite-components@v1.0.0-beta.23` dropped `calcite-icon`'s `filled` attribute and has a different naming convention for a few filled icons.
> fix(pick-list-item): update filled circle icon setup

- src/components/calcite-action/calcite-action.stories.ts
- src/components/calcite-fab/calcite-fab.stories.ts
docs: fix edge legacy stories.
removes the `undefined` text from showing up in edge legacy stories.
> docs(action,fab): fix edge legacy stories.

- support/prepublish.ts
Tone down `prepublish.ts` error messaging:
**before**
**after**
> chore: revisit prepublish error messaging

- src/components/calcite-pick-list/calcite-pick-list.stories.ts
- src/components/calcite-value-list/calcite-value-list.stories.ts
- src/demos/pick-list/advanced.html
**Related Issue:** #940
Icons in the component demos and storybooks updated to look less like radio buttons.
Also cleared out inline styling.
> feat: use less confusing icons in pick-list and value-list

- src/components/calcite-action/calcite-action.scss
- src/components/calcite-block/calcite-block.scss
- src/components/calcite-handle/calcite-handle.scss
- src/components/calcite-pick-list-item/calcite-pick-list-item.scss
- src/components/calcite-tip-manager/calcite-tip-manager.scss
- src/components/calcite-tip/calcite-tip.scss
- src/components/calcite-value-list-item/calcite-value-list-item.scss
- src/demos/tip/basic.html
- src/scss/mixins/_utilities.scss
**Related Issue:** #945 
* Add new :focus mixin to match calcite-components.
* Replace old mixin with new
* Added new mixin where needed
cc @macandcheese let me know if there's a way to pull those mixins in from calcite-components. I'm currently reproducing them.
> feat: replace focus ring mixin and added new mixin where needed

- src/components/calcite-block/calcite-block.scss
**Related Issue:** #941 
Fix for loading state in Block header.
> fix(block): loader UI bug

- src/components/calcite-panel/calcite-panel.scss
- src/demos/shell/demo-app-advanced-center-row.html
**Related Issue:** #952
Little tweak to handle when FAB is in a Panel inside ShellCenterRow and stuff goes sideways. Sideways like scrolling horizontally.
cc @kat10140
> feat(panel): tweak for FAB slot when h-scroll

- src/components/calcite-shell/calcite-shell.stories.ts
- src/components/calcite-shell/usage/advanced.md
- src/components/calcite-shell/usage/basic.md
CalciteTipManager should work in `center-row` slot
> docs(shell-center-row): tip-manager usage

- src/components/calcite-block-section/calcite-block-section.tsx
- src/demos/block/basic.html
**Related Issue:** #957
Add `calcite--rtl` to BlockSection.
This CSS class on Block wasn't affecting BlockSection.
> fix(block-section): added rtl check and css

- src/components/calcite-shell-center-row/calcite-shell-center-row.scss
- src/components/calcite-shell-panel/calcite-shell-panel.scss
**Related Issue:** #955 
* Only define borders on center-row when it's not detached
* move bg-color and border styles to center-row :host
* remove borders from shell-panel
> feat(shell-center-row, shell-panel): move and reduce styles

- src/components/calcite-filter/calcite-filter.scss
- src/components/calcite-filter/calcite-filter.tsx
- src/components/calcite-pick-list/shared-list-render.tsx
- src/demos/pick-list/advanced.html
**Related Issue:** #959
* Added an RTL check to CalciteFilter.
* Added and updated styles accordingly
- style linting asked for some rearrangement
* updated demo app to include filtering in pick-list in RTL
@driskull  I can't figure out how to get CalciteFilter to see an upstream `dir="rtl"`.
cc @AdelheidF
> fix(calcite-filter): added rtl check and updated styles

- src/components/calcite-tip-manager/calcite-tip-manager.scss
**Related Issue:** #945 
Updated the focus ring to be outset.
cc @kat10140
> fix(tip-manager): changed focus style to avoid hidden ring

- package.json
**Related Issue:** #936 
This uses `https://www.npmjs.com/package/touch` (npx) instead of relying on a 3rd-party git plugin.
> chore(changelog): use touch alternative

- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/components/calcite-action-pad/calcite-action-pad.tsx
- src/components/calcite-block-section/calcite-block-section.tsx
- src/components/calcite-block/calcite-block.tsx
- src/components/calcite-filter/calcite-filter.tsx
- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-panel/calcite-panel.tsx
- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-pick-list/calcite-pick-list.tsx
- src/components/calcite-pick-list/shared-list-logic.ts
- src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
- src/components/calcite-shell-panel/calcite-shell-panel.scss
- src/components/calcite-shell-panel/calcite-shell-panel.tsx
- src/components/calcite-shell/calcite-shell.e2e.ts
- src/components/calcite-shell/calcite-shell.tsx
- src/components/calcite-shell/resources.ts
- src/components/calcite-tip-manager/calcite-tip-manager.tsx
- src/components/calcite-tip/calcite-tip.tsx
- src/components/calcite-value-list-item/calcite-value-list-item.tsx
- src/components/calcite-value-list/calcite-value-list.tsx
- src/components/interfaces.ts
- src/components/utils/dom.ts
- src/demos/shell/block-configurations.html
- src/demos/shell/demo-app-advanced-2.html
- src/demos/shell/demo-app-advanced-center-row.html
- src/demos/shell/demo-app-advanced.html
- src/demos/shell/demo-app-full-window-reversed.html
- src/demos/shell/demo-app-full-window.html
- src/demos/shell/demo-app.html
- tsconfig.json
BREAKING CHANGE:
- Removed deprecated 'text-*' properties from action-bar, action-pad, block, block-section, filter, flow-item, panel, tip-manager, and tip.
- Removed deprecated 'layout' property from action-bar, action-pad, and shell-panel.
- Removed deprecated 'compact' property from pick-list-item, pick-list, value-list, and value-list-item.
- Removed deprecated `tip-manager` slot from shell.
> refactor!: Remove deprecated properties and slots from components

- src/components/calcite-action-bar/calcite-action-bar.stories.ts
- src/components/calcite-action-pad/calcite-action-pad.stories.ts
**Related Issue:** #910
Storybook knobs only support string, number, null and undefined as values, so it’s not possible to have one handle DOM references. This adds simple tooltip-specific stories.
> docs(action-bar, action-pad): add tooltip-prop stories

- package.json
**Related Issue:** #936
The most recent update (https://github.com/Esri/calcite-app-components/pull/969) did not clean up a temp file. 😅
> chore(changelog): clean up temp files generated when creating the preview

- src/components/calcite-flow-item/calcite-flow-item.tsx
- src/components/calcite-flow-item/resources.ts
- src/components/utils/dom.spec.ts
- src/components/utils/dom.ts
**Related Issue:** #498
Since slotted elements come from light DOM and only direct children are allowed to be slotted into an element (no nesting), this adds a property to the `getSlotted` options to only process direct children (true by default).
> refactor(dom): enhance getSlotted to process direct children

- .versionrc.json
This addresses the following warning:
```
[standard-version]: --changelogHeader will be removed in the next major release. Use --header.
```
> chore(standard-version): use changelogHeader replacement

- src/components/calcite-pick-list/calcite-pick-list.stories.ts
**Related Issue:** #965 
This adds a story to demonstrate how to nest pick list items.
> docs(pick-list): add story for nested items

- src/components/calcite-panel/calcite-panel.tsx
Inlines the focus ID type for `CalcitePanel#setFocus` to fix the Stencil build.
> chore(types): inline type for panel focus ID

- src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
- src/components/calcite-pick-list/calcite-pick-list.tsx
- src/components/calcite-pick-list/shared-list-logic.ts
- src/components/calcite-pick-list/shared-list-tests.ts
- src/components/calcite-value-list-item/calcite-value-list-item.tsx
- src/components/calcite-value-list/calcite-value-list.e2e.ts
- src/components/calcite-value-list/calcite-value-list.tsx
**Related Issue:** #986 
This ensures the handle element is focused right after browser rendering.
Additionally, this also fixes some ESLint errors and adds more assertions to test keyboard item-moving.
> fix(value-list): ensure keyboard-enabled DND stays active when moving items around

- src/components/calcite-action-bar/calcite-action-bar.e2e.ts
- src/components/calcite-action-bar/calcite-action-bar.tsx
- src/demos/action-bar/add-action-after-init.html
**Related Issue:** #1023 
Adds a MutationObserver to action-bar to watch for new children and enforces the current `expanded` state to them. Tried to replicate the usage of MutationObserver from other components.
> fix(action-bar): Sync expanded state with new children

- src/components/calcite-pick-list/calcite-pick-list.e2e.ts
- src/components/calcite-pick-list/shared-list-logic.ts
**Related Issue:** #1026 
This ensures that non-matching groups during filtering, whether nested (`slot=parent-item`) or not, are properly hidden.
cc @kevindoshier
> fix(pick-list): hide non-nested groups that do not match filter

- src/components/calcite-action/calcite-action.tsx
**Related Issue:** #1034
Before
After
> fix(action): fixed icon scales

- package.json
- support/ensureNonPrereleaseChangelog.ts
**Related Issue:** #1029 
This adds a new support script to that will help create a changelog without any prerelease tags in between versions.
> docs(changelog): ensure changelog includes entries from prereleases

- package-lock.json
- package.json
Updates `calcite-components` to latest for a type fix.
> build(deps): bump versions

- src/components/calcite-panel/calcite-panel.scss
- src/components/calcite-panel/calcite-panel.tsx
- src/components/calcite-panel/resources.ts
Should fix this:
https://github.com/Esri/calcite-components/issues/797
Should not cause this again:
https://github.com/Esri/calcite-app-components/issues/1000
Should not cause this again:
https://github.com/Esri/calcite-app-components/issues/1044
@driskull tested this with a stand-in histogram slider and with a div with similar styling. Neither applied the z-index fix, and it seemed to be working.
Hoping that @AdelheidF can test this using the next.
> fix(panel): remove slot-container and associated styles

- .storybook/utils.ts
This updates the component HTML util to handle boolean attributes correctly.
> docs: fix boolean attribute generation in story util

- src/components/calcite-sortable-list/calcite-sortable-list.e2e.ts
- src/components/calcite-value-list/calcite-value-list.e2e.ts
- src/components/calcite-value-list/calcite-value-list.tsx
- src/demos/value-list/advanced.html
- src/demos/value-list/basic.html
- src/tests/utils.ts
**Related Issue:** #1056
Adds `group` prop to `value-list` to allow drag and drop items across lists with the same group (requires `dragEnabled === true`).
* This also adds a e2e utility to help test DnD interactions and unskips previous DnD tests. 🛠️ 
* I'll cherry-pick this over to `calcite-components` when merged. 😄
* Since dragging between lists requires `dragEnabled` to be true, would it be better to rename the prop to `dragGroup` or something similar to indicate that they are linked?
* I had not considered using the keyboard to move items across lists, is this something we should support? cc @asangma
> feat(value-list): allow dragging items between lists
