src/components/calcite-action-bar/readme.md
src/components/calcite-block/readme.md
src/components/calcite-flow-item/readme.md
src/components/calcite-shell-panel/readme.md
src/components/calcite-shell/readme.md
src/components/calcite-tip/readme.md

**Related Issue:** #140 
@pr3tori4n can you have a look at the `info` and `link` slots for `calcite-tip` pls?

Slawt Dawk

---

src/components/calcite-block/calcite-block.scss
src/components/calcite-shell/calcite-shell.scss

**Related Issue:** #139. 
Added some styles for color
- Block
- Shell > footer

Added foreground styles

---

src/assets/styles/_color.scss
src/components/calcite-action/calcite-action.scss
src/demos/calcite-shell.html

**Related Issue:** #170. 
Zee stylez.

Disabled style for action

---

src/components/calcite-floating-panel/calcite-floating-panel.e2e.ts
src/components/calcite-floating-panel/calcite-floating-panel.tsx
src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
src/components/calcite-tip-manager/calcite-tip-manager.tsx
src/components/calcite-tip/calcite-tip.e2e.ts
src/components/calcite-tip/calcite-tip.tsx

**Related Issue:** #179
Add event for when a component is closed

Add event for when a component is closed

---

src/components/calcite-shell/readme.md

contextual panel fix #181

---

src/components/calcite-action-pad/calcite-action-pad.scss
src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.scss
src/demos/calcite-shell-rtl.html
src/demos/calcite-shell.html

**Related Issue:** #208 fix placement bug
CSS now uses `placement` instead of `position-type`

#208 fix placement bug

---

src/assets/styles/_base.scss
src/components/calcite-action-pad/calcite-action-pad.scss
src/components/calcite-flow-item/calcite-flow-item.scss
src/components/calcite-shell-floating-panel/calcite-shell-floating-panel.scss
src/components/calcite-tip-manager/calcite-tip-manager.scss

**Related Issue:**  #202
Bug: every component should be able to be hidden by attribute #202

Bug: every component should be able to be hidden by attribute

---

package-lock.json
package.json

Update Stencil to latest version.

@stencil/core@1.3.2

---

src/components/calcite-tip-manager/calcite-tip-manager.tsx
src/demos/calcite-tip-manager.html

**Related Issue:** #197 
rtl flips the chevrons, so logic added to flip them back.

pagination icons respect dir=rtl

---

src/components/calcite-demo-nav/calcite-demo-nav.scss
src/components/calcite-demo-nav/calcite-demo-nav.tsx

**Related Issue:** #213 
Turned the nav into a hamburger menu on mobile. Overdone, but simple and effective.

Mobile version of demo nav

---

src/components/calcite-action-bar/calcite-action-bar.e2e.ts
src/components/calcite-action-bar/calcite-action-bar.tsx
src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
src/components/calcite-shell-panel/calcite-shell-panel.tsx

**Related Issue:** #223
Enhancement: Add events to notify app when panel size has changed #223

Enhancement: Add events to notify app when panel size has changed #223

---

CHANGELOG.md

Something to hold us over until we automate the changelog

chore: initial changelog

---

src/demos/calcite-flow.html

**Related Issue:** #199
Small CSS change in the demo to improve mobile view.

fix: flow demo chang width to max-width

---

src/components/calcite-pick-list-item/calcite-pick-list-item.tsx

**Related Issue:** #
PickListItems can be tabbed to and selected/deselected by pressing "space"

PickList - keyboard toggles

---

package-lock.json
package.json
src/components/calcite-action-bar/calcite-action-bar.e2e.ts
src/components/calcite-panel/calcite-panel.e2e.ts
src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
src/components/calcite-tip-manager/calcite-tip-manager.scss
src/components/calcite-tip-manager/calcite-tip-manager.tsx
src/components/calcite-tip-manager/resources.ts
src/components/calcite-tip/calcite-tip.e2e.ts

- Update stencil to 1.5.3
- Fix tip manager test (needed key for h2)
- fix issue #276 (added two classes)
- await test `E2EElement.click()` uses
**Related Issue:** #276

Update stencil to 1.5.3

---

src/components/calcite-action-bar/calcite-action-bar.scss
src/components/calcite-shell/calcite-shell.scss

**Related Issue:** #286
Allow action bar to scroll. nix shell min height

Allow action bar to scroll. nix shell min height

---

package-lock.json
package.json

Adds NPM script to make dependency updating easier.
Uses https://www.npmjs.com/package/updtr to update all dependencies (runs tests on each one and only updates the passing ones) and commits on success.

Add dependency updater script.

---

.travis.yml
README.md
src/components/calcite-action-bar/calcite-action-bar.e2e.ts

**Related Issue:** #152
Sets up Travis CI!
Thanks for the assist @pr3tori4n!

Issue #152: Wire up Travis CI.

---

package-lock.json
package.json
src/components/calcite-tip-manager/calcite-tip-manager.e2e.ts
src/components/calcite-tip-manager/calcite-tip-manager.tsx

Update to Stencil core to pre-release 1.60-2.

Update to Stencil core to pre-release 1.60-2.

---

CHANGELOG.md
package-lock.json
package.json

Update to Stencil 1.6.1

---

src/components/calcite-flow-item/calcite-flow-item.tsx

Get rid of a div for the slot.

simplify slot

---

src/assets/styles/_base.scss
src/assets/styles/_layout.scss

**Related Issue:** #366
Added min-height and related CSS var.

fix(panel, flow-item): added min-height.

---

src/components/calcite-block-section/calcite-block-section.scss
src/demos/calcite-shell-full-window.html

**Related Issue:** #372
* Moved border to the bottom of block-section.
* Also updated the full-screen shell demo to have more realistic content.
cc @AdelheidF

style(block-section): move border to bottom.

---

src/components/calcite-pick-list-item/calcite-pick-list-item.tsx

**Related Issue:** https://github.com/Esri/calcite-app-components/commit/bc7ec4f19359010d474194a0c81058921ab6a57f#r35548754
Fix event bug

patch event to send item. Needs a followup test for this.

---

src/components/calcite-action/calcite-action.scss

**Related Issue:** #391
The stuff for the thing.

style(action): added animations for interactive

---

src/components/calcite-panel/calcite-panel.e2e.ts
src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
src/components/calcite-shell/calcite-shell.e2e.ts

**Related Issue:** #385 accessible testing for panel components
#385 accessible testing for panel components

#385 accessible testing for panel components

---

src/components/calcite-flow-item/calcite-flow-item.e2e.ts
src/components/calcite-flow/calcite-flow.e2e.ts

**Related Issue:** calcite flow tests #385
calcite flow tests #385

calcite flow tests #385

---

src/components/calcite-action-bar/calcite-action-bar.e2e.ts
src/components/calcite-action-group/calcite-action-group.e2e.ts
src/components/calcite-action-pad/calcite-action-pad.e2e.ts
src/components/calcite-action/calcite-action.e2e.ts

**Related Issue:** #385
#385 accessible action components

#385 accessible action components

---

package-lock.json
package.json

Update calcite components to 1.0.0-beta.11

 Update calcite components to 1.0.0-beta.11

---

src/components/calcite-shell/calcite-shell.scss

**Related Issue:** #393 remove shell min-width
Removes min-width restriction from the shell component

#393 remove shell min-width

---

src/components/calcite-flow-item/calcite-flow-item.scss
src/components/calcite-panel/calcite-panel.scss
src/demos/calcite-flow-item.html
src/demos/calcite-flow.html
src/demos/calcite-pick-list.html

**Related Issue:** #414
Moved relevant styles to **panel** and cleaned up styles.
cc @AdelheidF

bug(flow-item, panel): header text-overflow fix.

---

src/components/calcite-panel/calcite-panel.scss
src/components/calcite-value-list/calcite-value-list.scss

**Related Issue:** #418
When value-list was in a panel or when pick-list was in a panel, the padding in panel was causing issues.

style(panel, value-list): spacing tweaks/

---

src/assets/styles/_base.scss
src/components/calcite-block/calcite-block.scss

**Related Issue:** #427
CalciteBlock: Set color vars for dark theme.

CalciteBlock: Set color vars for dark theme.

---

.travis.yml
package.json

**Related Issue:** #431
Includes linting script in CI.

Issue #431: Include linting in CI.

---

src/components/calcite-pick-list-group/calcite-pick-list-group.scss

**Related Issue:** #493
Fixed style for pick-list-group heading.

style(pick-list-group): heading styling

---

CHANGELOG.md
src/demos/calcite-pick-list-advanced.html

Clean up the changelog for v4.3.0 and v4.3.1. Those releases have some irrelevant line items.

remove commit noise from changelog

---

src/components/calcite-shell/calcite-shell.scss
src/components/calcite-tip-manager/calcite-tip-manager.scss
src/demos/calcite-shell-full-window.html
src/demos/calcite-shell.html

**Related Issue:** #477
fix: Shell styling for TipManager

fix: Shell styling for TipManager

---

CONTRIBUTING.md
README.md

**Related Issue:** #523
Add Semantic PR readme/info

docs: Add Semantic PR readme/info

---

.lintstagedrc.json
package.json
tslint.json

Enables auto-fixing of [`no-unused-variable`](https://palantir.github.io/tslint/rules/no-unused-variable/).

Auto-fix unused variables

---

src/assets/styles/_animation.scss
src/assets/styles/_layout.scss

Also sneaking in setting the animation var correctly. 
**Related Issue:** #519
* Adding a pixel to base size
* update animation vars.

style: Updating base spacing to 16px

---

src/components/calcite-panel/calcite-panel.scss
src/components/calcite-panel/calcite-panel.tsx
src/demos/calcite-shell-full-window.html

**Related Issue:** #513
feat: CalcitePanel - Add scale property to set dynamic height #513

feat: CalcitePanel - Add scale property to set dynamic height #513

---

package-lock.json
package.json

chore(deps): Bump versions.

---

src/components/calcite-block/calcite-block.tsx
src/components/calcite-panel/calcite-panel.tsx
src/components/calcite-pick-list/shared-list-render.tsx
src/components/utils/CalciteScrim.tsx

**Related Issue:** #560
fix: calcite-block disabled state doesn't 'hide' slider handle #560

fix: calcite-block disabled state doesn't 'hide' slider handle #560

---

.travis.yml

change node version in travis.yml from latest-stable to latest-lts verrsion

Travis CI Node Version Update 

---

src/components/calcite-demo-nav/calcite-demo-nav.scss
src/components/calcite-demo-nav/calcite-demo-nav.tsx
src/demos/calcite-typography.html
src/demos/demos.css
src/demos/toggles.template

**Related Issue:** #463
Styles and reworked nav for demos.

Added styles and reworks for demos.

---

src/demos/calcite-flow.html

**Related Issue:** #612
Fix JS error in flow demo by removing unnecessary script.

fix: JS error in flow demo by removing unnecessary script.

---

src/components/calcite-action/readme.md
src/components/calcite-action/usage/basic.md

**Related Issue:** #619
calcite-action-usage documentation
cc @kat10140

docs: calcite-action-usage documentation

---

src/components/calcite-flow/calcite-flow.tsx

chore: refactor flow frame CSS

---

package-lock.json

Fixes vulnerabilities reported by `npm install`.
```
found 12 vulnerabilities (3 moderate, 9 high)
run `npm audit fix` to fix them, or `npm audit` for details
```

chore(deps): fix vulnerable deps

---

src/components/calcite-action-pad/usage/basic.md

**Related Issue:** #619 #635 
snips

docs: action pad snips

---

.gitignore

chore: clean up ignore file

---

.storybook/resources.ts
src/components/calcite-action-bar/calcite-action-bar.stories.ts
src/components/calcite-action-bar/resources.ts
src/components/calcite-action-pad/calcite-action-pad.stories.ts
src/components/calcite-action/calcite-action.stories.ts
src/components/calcite-action/calcite-action.tsx
src/components/calcite-action/resources.ts
src/components/interfaces.ts

**Related Issue:** #644
Docs: [Storybook] Action component stories

docs: [Storybook] Action component stories

---

.storybook/resources.ts
src/components/calcite-flow/calcite-flow.stories.ts
src/components/calcite-panel/calcite-panel.scss
src/components/calcite-panel/calcite-panel.stories.ts
src/components/calcite-panel/calcite-panel.tsx
src/components/calcite-panel/resources.ts
src/components/calcite-tip/calcite-tip.stories.ts
src/components/interfaces.ts

**Related Issue:** #644
docs: [Storybook] Flow & Panel component stories

docs: [Storybook] Flow & Panel component stories

---

.storybook/resources.ts
src/components/calcite-action-bar/calcite-action-bar.stories.ts
src/components/calcite-action-pad/calcite-action-pad.stories.ts
src/components/calcite-action/calcite-action.stories.ts
src/components/calcite-panel/calcite-panel.stories.ts
src/components/calcite-shell-panel/resources.ts
src/components/calcite-shell/calcite-shell.stories.ts
src/components/calcite-tip/calcite-tip.stories.ts

**Related Issue:** #644
docs: [Storybook] Shell component stories
- Moved some HTML constants into the function since they were causing issues.
- Updated `createAction` utility
- Created basic and advanced stories for shell

docs: [Storybook] Shell component stories

---

package-lock.json
package.json

chore: bump versions

---

.storybook/config.ts

**Related Issue:** none
chore: turn on storybook toolbar so docs can be toggled.

chore: turn on storybook toolbar so docs can be toggled.

---

src/components/calcite-flow-item/calcite-flow-item.tsx
src/components/calcite-panel/calcite-panel.tsx

docs: fixed footer actions slot doc to use button #660"

---

src/components/calcite-flow-item/calcite-flow-item.tsx
src/components/calcite-shell-panel/calcite-shell-panel.e2e.ts
src/components/calcite-shell-panel/calcite-shell-panel.tsx
src/components/calcite-shell/calcite-shell.stories.ts
src/components/calcite-shell/resources.ts

**Related Issue:** #686
Enhancement: ShellPanel. Add tests and stories for detached mode and panel heigh-scale prop

chore: Panels knobs and test

---

src/components/calcite-panel/usage/basic.md

docs: calcite panel snippets

---

src/components/calcite-flow/usage/basic.md

docs: calcite flow snippets

---

src/components/calcite-shell/usage/advanced.md
src/components/calcite-shell/usage/basic.md
src/demos/shell/basic.html

docs: calcite shell snippets

---

src/demos/shell/basic.html

**Related Issue:** #none i just need to revert 😬

docs: reverting the basic demo that i just plastered over

---

src/components/calcite-tip/usage/basic.md
src/demos/shell/basic.html

docs: calcite tip snippets

---

src/components/calcite-tip-manager/usage/basic.md
src/demos/shell/basic.html

docs: calcite tip manager snippets

---

src/components/calcite-flow-item/calcite-flow-item.e2e.ts
src/components/calcite-flow-item/calcite-flow-item.tsx
src/components/calcite-flow-item/resources.ts
src/components/calcite-flow/calcite-flow.stories.ts
src/components/calcite-panel/calcite-panel.e2e.ts
src/components/calcite-panel/calcite-panel.stories.ts
src/components/calcite-panel/calcite-panel.tsx
src/components/calcite-panel/resources.ts

chore: Add slots const for panel and flow

chore: Add slots const for panel and flow

---

src/components/calcite-pick-list/usage/basic.md

docs: calcite pick list snippets

---

src/components/calcite-action-bar/calcite-action-bar.stories.ts
src/components/calcite-action-pad/calcite-action-pad.stories.ts
src/components/calcite-action/calcite-action.stories.ts
src/components/calcite-flow/calcite-flow.stories.ts
src/components/calcite-panel/calcite-panel.stories.ts
src/components/calcite-pick-list/calcite-pick-list.stories.ts
src/components/calcite-shell/calcite-shell.stories.ts
src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
src/components/calcite-tip/calcite-tip.stories.ts
src/components/calcite-value-list/calcite-value-list.stories.ts

**Related Issue:** #722
docs: Storybook - Add knob for RTL/LTR toggle for each component

docs: Storybook - Add knob for RTL/LTR toggle for each component

---

src/components/calcite-action/calcite-action.scss
src/components/calcite-filter/calcite-filter.scss
src/components/calcite-pick-list-item/calcite-pick-list-item.scss

**Related Issue:** none
- Focus styles where there are hover styles.

fix: focus button styles

---

src/components/calcite-action/calcite-action.scss

Action width not displaying correctly on Edge. This fixes it.

fix: action display on edge.

---

src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
src/components/calcite-pick-list/calcite-pick-list.stories.ts
src/components/calcite-value-list-item/calcite-value-list-item.tsx
src/components/calcite-value-list/calcite-value-list.stories.ts

**Related Issue:** #728 
This is a BREAKING CHANGE which renames the `secondaryAction` slot for pickList and valueList to `secondary-action`.

feat: BREAKING CHANGE rename secondary-action slot

---

src/components/calcite-pick-list/usage/basic.md
src/components/calcite-shell/usage/advanced.md
src/components/calcite-value-list/usage/basic.md
src/demos/block/with-value-list.html
src/demos/pick-list/advanced.html
src/demos/pick-list/basic.html
src/demos/pick-list/simple.html
src/demos/shell/demo-app-full-window-reversed.html
src/demos/shell/demo-app-full-window.html
src/demos/value-list/advanced.html
src/demos/value-list/basic.html

**Related Issue:** #728
Find/replace secondaryAction with secondary-action

docs:  replace secondaryAction with secondary-action

---

src/components/calcite-flow-item/calcite-flow-item.tsx
src/components/calcite-flow-item/resources.ts

chore: cleanup flow slots

---

package-lock.json
package.json

chore: bump stencil to "1.9.0-15"

chore: bump stencil

---

src/components/calcite-pick-list/shared-list-logic.ts
src/components/calcite-value-list/calcite-value-list.tsx

This improves types that would trip up the build. 
**Note**: I'll use https://github.com/Esri/calcite-app-components/issues/492 as an opportunity to clean this up.
cc @asangma @kat10140

build: fix shared list logic types.

---

package-lock.json
package.json

build(deps): bump versions

---

src/components/calcite-action/calcite-action.tsx
src/components/calcite-flow-item/calcite-flow-item.e2e.ts
src/components/calcite-flow-item/calcite-flow-item.tsx
src/demos/flow-item/basic.html
src/demos/flow/adding-items.html
src/demos/flow/basic.html
src/demos/shell/demo-app-full-window-reversed.html
src/demos/shell/demo-app-full-window.html
src/demos/shell/demo-app-rtl.html
src/demos/shell/demo-app.html

**Related Issue:** #882
- Fix counting the number of actions based on slot occurrences instead of child content.
- Clean up test apps
- Fix tests

feat(flow-item): Fix count for menu-actions

---

package-lock.json

This addresses some vulnerable deps reported by `npm audit`.

build(deps): fix vulnerable deps

---

src/components/calcite-action-bar/usage/basic.md
src/components/calcite-action/calcite-action.e2e.ts
src/components/calcite-flow/calcite-flow.stories.ts
src/components/calcite-flow/usage/basic.md
src/components/calcite-shell/calcite-shell.stories.ts
src/demos/action-bar/basic.html
src/demos/flow/adding-items.html

docs: Fix slot usage for stories and usage

docs: Fix slot usage for stories and markdown

---

src/components/calcite-pick-list-item/calcite-pick-list-item.tsx
src/components/calcite-pick-list-item/resources.ts

fix(pick-list, value-list): Fix icon for selected circle

fix(pick-list, value-list): Fix icon for selected circle

---

src/demos/action-bar/add-action-after-init.html
src/demos/action-bar/basic.html
src/demos/action-pad/basic.html
src/demos/action/basic.html
src/demos/block/with-value-list.html
src/demos/flow/adding-items.html
src/demos/pick-list/advanced.html
src/demos/pick-list/basic.html
src/demos/shell/demo-app-full-window-reversed.html
src/demos/shell/demo-app-full-window.html
src/demos/shell/demo-app-rtl.html
src/demos/shell/demo-app.html
src/demos/shell/panel-with-action-bar.html
src/demos/value-list/advanced.html
src/demos/value-list/basic.html
src/demos/value-list/double-action.html
src/demos/value-list/value-update.html

Removed use of calcite-icon in html files when use of calcite-action with the icon property is sufficient

chore: remove use of calcite-icon if possible

---

src/demos/value-list/advanced.html

chore: fix test app

---

src/components/calcite-action/calcite-action.e2e.ts
src/components/calcite-action/calcite-action.tsx
src/demos/action/add-action-icon-after-init.html

fix(action): Support slotting icon after initialization

fix(action): Support slotting icon after initialization

---

src/components/calcite-action/calcite-action.tsx

chore: use the force
https://github.com/Esri/calcite-app-components/pull/913#discussion_r402659302

chore: use the force

---

README.md

**Related Issue:** #924
Docs: document supported browsers

docs: document supported browsers #924

---

src/1-introduction.stories.mdx

docs: Update storybook home info and link to calcite-components

docs: Update storybook home info and link to calcite-components

---

.storybook/main.ts
package-lock.json
package.json
src/components/calcite-action-bar/calcite-action-bar.stories.ts
src/components/calcite-action-pad/calcite-action-pad.stories.ts
src/components/calcite-action/calcite-action.stories.ts
src/components/calcite-block/calcite-block.stories.ts
src/components/calcite-block/calcite-block.tsx
src/components/calcite-fab/calcite-fab.stories.ts
src/components/calcite-flow/calcite-flow.stories.ts
src/components/calcite-panel/calcite-panel.stories.ts
src/components/calcite-panel/calcite-panel.tsx
src/components/calcite-pick-list/calcite-pick-list.stories.ts
src/components/calcite-pick-list/shared-list-render.tsx
src/components/calcite-shell/calcite-shell.stories.ts
src/components/calcite-tip-manager/calcite-tip-manager.stories.ts
src/components/calcite-tip-manager/calcite-tip-manager.tsx
src/components/calcite-tip/calcite-tip.stories.ts
src/components/calcite-value-list/calcite-value-list.stories.ts

Add a11y addon to storybook to easily test
We would need to import it to all stories and add our aXe configuration.
https://github.com/storybookjs/storybook/tree/master/addons/a11y#parameters
What are your thoughts @jcfranco ?
https://github.com/storybookjs/storybook/tree/master/addons/a11y

docs: Add a11y to storybook

---

src/components/calcite-pick-list/shared-list-render.tsx
src/components/utils/CalciteExpandToggle.tsx

refactor: fix build errors

---

package-lock.json
package.json

chore(deps): bump versions

---

package-lock.json

chore(deps): fix npm audit

---

.travis.yml

chore: use Travis environment vars for notification setup

---

src/components/calcite-block/calcite-block.tsx
src/components/calcite-flow-item/calcite-flow-item.tsx
src/components/calcite-panel/calcite-panel.tsx
src/components/calcite-pick-list/shared-list-render.tsx
src/components/utils/dom.ts

**Related Issue:** #618
chore: fix scrim theme

chore: fix scrim theme

---

.travis.yml

This encrypts the notification setup. Based on https://stackoverflow.com/a/33783088/194216, it seems the environment vars weren't being picked up.

chore: encrypted notification settings

---

src/components/calcite-panel/calcite-panel.scss
src/components/calcite-panel/calcite-panel.tsx
src/components/calcite-panel/resources.ts
src/demos/panel/basic.html

**Related Issue:** #1000
Make sure the FAB is always stacked higher than user content within the default slot.

fix(panel, flow-item): Make sure the FAB is always stacked higher than slot content.

---

src/components/calcite-flow-item/calcite-flow-item.scss
src/components/calcite-flow-item/calcite-flow-item.tsx

**Related Issue:** #1009
feat(flow-item): Use calcite-popover for menu actions

feat(flow-item): Use calcite-popover for menu actions

---

src/components/calcite-action/calcite-action.tsx
src/demos/shell/demo-app-advanced.html

**Related Issue:** #1020
Fix how icon is scaled in Action.
cc @kat10140

fix(action): fix icon scale

---

src/components/calcite-panel/calcite-panel.scss

**Related Issue:** #1044
100% one line!

fix(panel): slot-container height

---

package-lock.json
package.json

Moved dev-dependency and removed unused one.

chore(deps): tidy up
